import Link from "next/link";

export default function Home() {
  return (
    <div className="py-12">
      <section className="prose">
        <div data-show="professional">
          <p>
            I&rsquo;m Zarak. Senior Data Scientist at BMW Group, based in the
            New York area.
          </p>
          <p>
            I build ML systems and AI agents for things that have to actually
            work &mdash; clinical EHR operations, automotive safety, and the
            unglamorous infrastructure underneath both.
          </p>
          <p className="text-muted">
            Most of what I make ends up in production at companies that care
            more about reliability than novelty.
          </p>
        </div>

        <div data-show="personal">
          <p>
            Hi, I&rsquo;m Zarak. Outside of the day job I tinker.
          </p>
          <p>
            Cold-outreach pipelines, daily LinkedIn carousels generated by an
            agent, an Instagram bot that I keep meaning to retire. Small tools
            that automate the parts of life I don&rsquo;t want to do myself.
          </p>
          <p className="text-muted">
            I write occasionally about what I&rsquo;ve learned &mdash; usually
            after I&rsquo;ve broken something twice.
          </p>
        </div>
      </section>

      <section className="mt-16 grid gap-3 text-sm">
        <Link
          href="/writing"
          className="flex items-baseline justify-between border-t border-rule pt-3"
        >
          <span>Writing</span>
          <span className="text-muted">notes &amp; posts</span>
        </Link>
        <Link
          href="/projects"
          className="flex items-baseline justify-between border-t border-rule pt-3"
        >
          <span>Projects</span>
          <span className="text-muted">things I&rsquo;ve shipped</span>
        </Link>
      </section>
    </div>
  );
}
